services:
  # bot:
  #   container_name: backend-bot
  #   restart: unless-stopped
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  # postgres:
  #   container_name: backend-postgres
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=engagelagos
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  redis:
    container_name: backend-redis
    image: redis:latest
    command: [redis-server, --maxmemory-policy, noeviction]
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
  minio:
    container_name: backend-minio
    image: minio/minio:latest
    command: [minio, server, /data, --console-address, ":9001"]
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
      
    volumes:
      - ./minio_data:/data
    healthcheck:
      test: [CMD, mc, ready, local]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  redis_data:
  minio_data:
  locals3root:

networks:
  default: {}
