services:
  postgres:
    container_name: backend-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=0760b385cf6e770236cb3729
      - POSTGRES_DB=backend
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: backend-redis
    image: redis:latest
    command: [redis-server, --maxmemory-policy, noeviction]
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  minio:
    container_name: backend-minio
    image: minio/minio:latest
    command: [minio, server, /data, --console-address, ":9001"]
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=backend
      - MINIO_SECRET_KEY=0760b385cf6e770236cb3729
    volumes:
      - minio_data:/data
    healthcheck:
      test: [CMD, mc, ready, local]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  default: {}
